{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:39:40.746300Z",
     "start_time": "2018-07-17T19:39:40.719256Z"
    },
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "u'/opt/localuser/Work/pydev/spiketag/demo'"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:39:40.905233Z",
     "start_time": "2018-07-17T19:39:40.883215Z"
    }
   },
   "outputs": [],
   "source": [
    "%load_ext autoreload"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:39:41.064361Z",
     "start_time": "2018-07-17T19:39:41.058505Z"
    }
   },
   "outputs": [],
   "source": [
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:39:41.491149Z",
     "start_time": "2018-07-17T19:39:41.233833Z"
    },
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Populating the interactive namespace from numpy and matplotlib\n"
     ]
    }
   ],
   "source": [
    "%pylab inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:39:41.512971Z",
     "start_time": "2018-07-17T19:39:41.496765Z"
    }
   },
   "outputs": [],
   "source": [
    "%gui qt"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## load and view the probe geometry"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:39:53.579029Z",
     "start_time": "2018-07-17T19:39:52.330493Z"
    },
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "from spiketag.probe import prb_bowtie_LL as prb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:39:54.458318Z",
     "start_time": "2018-07-17T19:39:53.966584Z"
    },
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/localuser/anaconda2/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.\n",
      "  \"You should import from traitlets.config instead.\", ShimWarning)\n"
     ]
    }
   ],
   "source": [
    "prb.show(font_size=30)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Sort"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:40:09.589573Z",
     "start_time": "2018-07-17T19:40:09.539789Z"
    }
   },
   "outputs": [],
   "source": [
    "prb.fs =25000.\n",
    "prb.n_ch = 160\n",
    "prb.reorder_by_chip = True\n",
    "prb._nchips = 5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:40:10.348815Z",
     "start_time": "2018-07-17T19:40:10.304595Z"
    }
   },
   "outputs": [],
   "source": [
    "from spiketag.mvc.Control import controller"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2018-07-17 21:58:53,364 - spiketag - INFO - load mua data\n",
      "2018-07-17 21:58:53,367 - spiketag - INFO - #############  load data  ###################\n",
      "2018-07-17 21:58:53,368 - spiketag - INFO - /data1/spiketag_demo/mua.bin loaded, it contains: \n",
      "2018-07-17 21:58:53,369 - spiketag - INFO - 17059414 * 160 points (10918024960 bytes) \n",
      "2018-07-17 21:58:53,371 - spiketag - INFO - 160 channels with sampling rate of 25000.0000 \n",
      "2018-07-17 21:58:53,373 - spiketag - INFO - 682.377 secs (11.373 mins) of data\n",
      "2018-07-17 21:58:53,374 - spiketag - INFO - #############################################\n"
     ]
    }
   ],
   "source": [
    "ctrl = controller(mua_filename='/data1/spiketag_demo/mua.bin',\n",
    "                  spk_filename='/data1/spiketag_demo/spk.bin', \n",
    "                  probe=prb, binary_radix=13)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(6, array([ 0, 31, 34, 47]))\n"
     ]
    }
   ],
   "source": [
    "ctrl.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:44:13.514575Z",
     "start_time": "2018-07-17T19:44:13.272737Z"
    },
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "delete (2,) spikes\n",
      "delete (29,) spikes\n",
      "delete (19,) spikes\n",
      "delete (12,) spikes\n",
      "delete (13,) spikes\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 413, in keyPressEvent\n",
      "    self._keyEvent(self._vispy_canvas.events.key_press, ev)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 428, in _keyEvent\n",
      "    func(native=ev, key=key, text=text_type(ev.text()), modifiers=mod)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 535, in on_key_press\n",
      "    if len(self.selected_spk) > 0:\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 331, in selected_spk\n",
      "    selected_spk = self.clu.local2global(self._selected)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 104, in local2global\n",
      "    global_idx = np.append(global_idx,self._glo_id(clu_no, local_idx, sorted=False))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 131, in _glo_id\n",
      "    glo_idx = self.index[selected_clu][sub_idx]\n",
      "IndexError: index 2756 is out of bounds for axis 1 with size 2756\n",
      "ERROR: Invoking <bound method spike_view.on_key_press of <spike_view (PyQt5) at 0x7fec88b2b3d0>> for KeyEvent\n",
      "2018-07-17 21:42:39,436 - spiketag - ERROR - Move spikes failure: index 2756 is out of bounds for axis 1 with size 2756\n",
      "2018-07-17 21:42:39,438 - spiketag - ERROR - Move selected spikes {0: array([ 228,  331,  771,  826, 1327, 1355, 1429, 1431, 1624, 1820, 2631,\n",
      "       2755, 2756]), 1: array([ 87, 111])} to target clu no 1. \n",
      "2018-07-17 21:42:39,448 - spiketag - ERROR - Current cluster index is {0: array([    1,     3,     4, ..., 24044, 24060, 24151]), 1: array([   65,   231,   249,   658,   705,   707,   708,   720,   722,\n",
      "         734,   736,   746,   749,   752,   754,   761,   765,   766,\n",
      "         768,   778,   780,   787,   791,   796,   798,   800,   884,\n",
      "         890,   893,   895,   900,   908,   909,   910,   918,   922,\n",
      "         935,   938,   939,   957,   958,   959,   961,  1494,  1497,\n",
      "        1585,  1608,  1622,  1624,  1628,  1630,  1631,  1634,  1637,\n",
      "        1642,  1647,  1649,  1650,  1651,  1657,  1658,  1661,  1666,\n",
      "        1675,  2244,  2807,  3427,  3526,  4046,  4048,  4307,  4348,\n",
      "        4870,  5247,  5248,  5250,  5251,  7659,  7749,  9179,  9182,\n",
      "        9183, 10183, 10217, 10219, 10235, 10258, 10306, 10344, 10348,\n",
      "       10383, 10516, 10518, 10570, 10687, 10719, 10722, 10726, 10729,\n",
      "       10730, 10734, 10747, 10752, 10759, 10764, 10765, 10771, 10776,\n",
      "       10778, 10779, 10781, 10825, 11580, 11585, 11611, 11729, 11742,\n",
      "       11743, 11751, 11768, 11778, 11780, 11781, 11889, 11890, 11902,\n",
      "       12029, 12033, 12034, 12043, 12044, 12046, 12050, 12053, 12135,\n",
      "       12139, 12140, 12272, 12283, 12408, 12412, 12413, 12414, 12415,\n",
      "       12422, 12423, 12429, 12431, 12433, 12436, 12437, 12438, 12445,\n",
      "       12446, 12447, 12448, 12456, 12457, 12459, 12468, 12469, 12471,\n",
      "       12474, 12478, 12500, 12527, 12529, 12530, 12531, 12534, 12538,\n",
      "       12539, 12543, 12668, 12671, 12672, 12673, 12674, 12675, 12681,\n",
      "       12683, 12685, 12686, 12687, 12690, 12692, 12693, 12704, 12705,\n",
      "       12706, 12707, 12710, 12711, 12712, 12713, 12716, 12727, 12729,\n",
      "       12730, 12731, 12732, 12735, 12742, 12744, 12745, 12746, 12747,\n",
      "       12752, 12753, 12754, 12755, 12763, 12764, 12767, 12770, 12771,\n",
      "       12773, 12777, 12779, 12780, 12781, 12782, 12783, 12788, 12794,\n",
      "       12795, 12796, 12797, 12804, 12807, 12808, 12809, 12810, 12811,\n",
      "       12813, 12815, 12818, 12819, 12848, 12849, 12850, 12852, 12853,\n",
      "       12854, 12861, 12862, 12863, 12864, 12865, 12866, 12887, 12888,\n",
      "       12889, 12890, 12891, 12893, 12894, 12895, 12910, 12912, 12913,\n",
      "       12915, 12926, 12928, 12940, 12943, 12945, 12946, 12948, 12952,\n",
      "       12954, 12955, 12956, 12957, 12958, 12959, 12960, 12961, 12967,\n",
      "       12970, 12971, 12973, 12981, 12983, 12984, 12994, 12996, 12997,\n",
      "       12998, 12999, 13000, 13002, 13006, 13007, 13008, 13020, 13023,\n",
      "       13025, 13027, 13029, 13032, 13035, 13037, 13038, 13039, 13040,\n",
      "       13041, 13043, 13044, 13047, 13049, 13056, 13057, 13058, 13059,\n",
      "       13060, 13067, 13068, 13069, 13070, 13071, 13072, 13074, 13078,\n",
      "       13080, 13084, 13087, 13144, 13155, 13161, 13175, 13177, 13178,\n",
      "       13180, 13189, 13191, 13192, 13207, 13210, 13211, 13212, 13220,\n",
      "       13221, 13222, 13223, 13224, 13229, 13230, 13231, 13232, 13233,\n",
      "       13238, 13243, 13244, 13251, 13252, 13253, 13261, 13262, 13264,\n",
      "       13266, 13268, 13281, 13282, 13284, 13307, 13318, 13321, 13322,\n",
      "       13323, 13329, 13330, 13331, 13332, 13333, 13334, 13388, 13391,\n",
      "       13392, 13393, 13394, 13399, 13401, 13403, 13404, 13405, 13406,\n",
      "       13413, 13427, 13442, 13443, 13455, 13462, 13463, 13486, 13487,\n",
      "       13488, 13494, 13499, 13504, 13506, 13530, 13547, 13550, 13560,\n",
      "       13568, 13573, 13595, 13597, 13598, 13600, 13602, 13624, 13630,\n",
      "       13631, 13632, 13635, 13636, 13637, 13638, 13639, 13642, 13643,\n",
      "       13646, 13647, 13649, 13652, 13653, 13655, 13658, 13661, 13675,\n",
      "       13676, 13677, 13678, 13679, 13682, 13700, 13731, 13733, 13734,\n",
      "       13741, 13742, 13743, 13750, 13754, 13755, 13761, 13765, 13766,\n",
      "       13767, 13774, 13777, 13796, 13797, 13798, 13800, 13804, 13810,\n",
      "       13811, 13820, 13821, 13822, 13826, 13827, 13829, 13830, 13834,\n",
      "       13835, 13836, 13844, 13848, 13860, 13973, 13974, 13989, 13997,\n",
      "       13999, 14003, 14004, 14006, 14008, 14009, 14030, 14036, 14039,\n",
      "       14048, 14056, 14058, 14059, 14061, 14066, 14067, 14068, 14070,\n",
      "       14075, 14077, 14084, 14087, 14092, 14093, 14095, 14099, 14100,\n",
      "       14109, 14110, 14111, 14131, 14132, 14159, 14162, 14171, 14185,\n",
      "       14270, 14271, 14275, 14323, 14325, 14326, 14327, 14330, 14335,\n",
      "       14338, 14340, 14341, 14343, 14344, 14352, 14356, 14361, 14363,\n",
      "       14372, 14375, 14376, 14377, 14385, 14416, 14417, 14421, 14423,\n",
      "       14489, 14490, 14491, 14496, 14506, 14509, 14516, 14517, 14518,\n",
      "       14521, 14522, 14523, 14526, 14536, 14546, 14561, 14569, 14570,\n",
      "       14572, 14573, 14575, 14607, 14608, 14652, 14690, 14694, 14696,\n",
      "       14725, 14726, 14875, 14914, 14978, 15034, 15060, 15062, 15120,\n",
      "       15121, 15125, 15129, 15134, 15146, 15149, 15163, 15166, 15174,\n",
      "       15193, 15197, 15198, 15199, 15349, 15360, 15368, 15369, 15389,\n",
      "       15390, 15405, 15415, 15421, 15435, 15439, 15440, 15446, 15476,\n",
      "       15486, 15488, 15500, 15982, 16138, 16214, 16215, 16231, 16234,\n",
      "       16260, 16261, 16262, 16269, 16270, 16272, 16273, 16275, 16281,\n",
      "       16282, 16283, 16298, 16301, 16323, 16348, 16386, 16788, 16824,\n",
      "       17063, 17095, 17125, 17172, 17179, 17182, 17184, 17186, 17193,\n",
      "       17195, 17197, 17200, 17203, 17205, 17207, 17208, 17209, 17210,\n",
      "       17211, 17212, 17416, 17423, 17425, 17427, 17767, 17775, 17777,\n",
      "       17779, 17787, 17789, 17795, 17796, 17801, 17825, 17858, 18476,\n",
      "       18477, 18500, 18508, 18759, 19001, 20096, 20330, 20331, 20476,\n",
      "       21171, 21375, 21396, 21397, 21402, 21403, 21413, 21434, 21435,\n",
      "       21438, 21439, 21440, 21441, 21487, 21489, 21528, 21562, 21774,\n",
      "       21897, 22510, 22561, 22576, 22577, 22585, 22586, 22588, 22591,\n",
      "       22592, 22709, 22842, 22946, 22953, 22955, 22972, 22977, 22978,\n",
      "       22981, 22984, 22985, 22987, 22988, 22990, 22992, 23002, 23197,\n",
      "       23925, 23948, 23949, 23981]), 2: array([    0,     2,     5, ..., 24222, 24223, 24224]), 3: array([ 4850,  6551,  7442,  7444,  7451,  8798, 11962, 11967, 11968,\n",
      "       16022, 18412, 18417, 18978, 20092, 20225, 22844, 22880, 23689,\n",
      "       23748]), 4: array([  207,   209,   211, ..., 24182, 24183, 24196])}.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "delete (2,) spikes\n",
      "delete (5,) spikes\n",
      "delete (5,) spikes\n",
      "delete (1,) spikes\n",
      "delete (4,) spikes\n",
      "delete (2,) spikes\n",
      "delete (11,) spikes\n",
      "delete (2,) spikes\n",
      "delete (3,) spikes\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2018-07-17 21:44:44,696 - spiketag - DEBUG - ctree view expand clustier 24196 here\n",
      "2018-07-17 21:45:11,820 - spiketag - DEBUG - ctree view expand clustier 24197 here\n",
      "2018-07-17 21:45:18,155 - spiketag - DEBUG - ctree view expand clustier 24199 here\n",
      "2018-07-17 21:45:36,772 - spiketag - DEBUG - ctree view expand clustier 24201 here\n"
     ]
    }
   ],
   "source": [
    "!mkdir /data1/spiketag_demo/spiketag"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:43:43.801396Z",
     "start_time": "2018-07-17T19:43:43.387277Z"
    }
   },
   "outputs": [],
   "source": [
    "ctrl.save('/data1/spiketag_demo/spiketag/test')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:40:58.488032Z",
     "start_time": "2018-07-17T19:40:58.452909Z"
    }
   },
   "source": [
    "## Sort based on previous saved spiketag"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:40:09.589573Z",
     "start_time": "2018-07-17T19:40:09.539789Z"
    }
   },
   "outputs": [],
   "source": [
    "prb.fs =25000.\n",
    "prb.n_ch = 160\n",
    "prb.reorder_by_chip = True\n",
    "prb._nchips = 5"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:40:10.348815Z",
     "start_time": "2018-07-17T19:40:10.304595Z"
    }
   },
   "outputs": [],
   "source": [
    "from spiketag.mvc.Control import controller"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2018-07-17T19:44:08.441908Z",
     "start_time": "2018-07-17T19:43:57.865512Z"
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2018-07-17 22:01:31,397 - spiketag - INFO - load spktag file\n",
      "2018-07-17 22:01:32,613 - spiketag - INFO - load mua data for wave view\n",
      "2018-07-17 22:01:32,616 - spiketag - INFO - #############  load data  ###################\n",
      "2018-07-17 22:01:32,618 - spiketag - INFO - /data1/spiketag_demo/mua.bin loaded, it contains: \n",
      "2018-07-17 22:01:32,620 - spiketag - INFO - 17059414 * 160 points (10918024960 bytes) \n",
      "2018-07-17 22:01:32,622 - spiketag - INFO - 160 channels with sampling rate of 25000.0000 \n",
      "2018-07-17 22:01:32,624 - spiketag - INFO - 682.377 secs (11.373 mins) of data\n",
      "2018-07-17 22:01:32,625 - spiketag - INFO - #############################################\n",
      "2018-07-17 22:01:33,905 - spiketag - INFO - reordered with nchips=5 and nch_perchip=32\n",
      "2018-07-17 22:01:37,273 - spiketag - INFO - processing folder: /data1/spiketag_demo/\n",
      "2018-07-17 22:01:37,314 - spiketag - INFO - raw data have 655193 spks\n",
      "2018-07-17 22:01:37,316 - spiketag - INFO - ----------------success------------------\n",
      "2018-07-17 22:01:37,317 - spiketag - INFO -  \n",
      "2018-07-17 22:01:37,320 - spiketag - INFO - Model.spktag is generated, nspk:508026\n"
     ]
    }
   ],
   "source": [
    "ctrl = controller('/data1/spiketag_demo/mua.bin', \n",
    "                  '/data1/spiketag_demo/spk.bin', \n",
    "                  prb, spktag_filename='/data1/spiketag_demo/spiketag/test')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24901 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24871 is out of bounds for axis 1 with size 24728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24871 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24871 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24871 is out of bounds for axis 1 with size 24728\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n",
      "WARNING: Traceback (most recent call last):\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 174, in _run_module_as_main\n",
      "    \"__main__\", fname, loader, pkg_name)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/runpy.py\", line 72, in _run_code\n",
      "    exec code in run_globals\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 832, in start\n",
      "    self._run_callback(self._callbacks.popleft())\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/ioloop.py\", line 605, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py\", line 263, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 123, in loop_qt5\n",
      "    return loop_qt4(kernel)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 111, in loop_qt4\n",
      "    _loop_qt(kernel.app)\n",
      "  File \"/opt/localuser/anaconda2/lib/python2.7/site-packages/ipykernel/eventloops.py\", line 95, in _loop_qt\n",
      "    app.exec_()\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/backends/_qt.py\", line 387, in mouseMoveEvent\n",
      "    modifiers=self._modifiers(ev),\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/app/base.py\", line 202, in _vispy_mouse_move\n",
      "    ev = self._vispy_canvas.events.mouse_move(**kwargs)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 455, in __call__\n",
      "    self._invoke_callback(cb, event)\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 475, in _invoke_callback\n",
      "    self, cb_event=(cb, event))\n",
      "  << caught exception here: >>\n",
      "  File \"/opt/localuser/Work/pydev/vispy/vispy/util/event.py\", line 471, in _invoke_callback\n",
      "    cb(event)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 76, in on_mouse_move\n",
      "    self._select(current_cluster)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/ctree_view.py\", line 178, in _select\n",
      "    self._clu.select(global_idx)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 155, in select\n",
      "    self.emit('select', action='select', caller=caller)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/utils/utils.py\", line 160, in emit\n",
      "    res.append(callback(*args, **kwargs))\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/view/spike_view.py\", line 114, in on_select\n",
      "    self._selected = self.clu.global2local(self.clu.selectlist)\n",
      "  File \"/opt/localuser/Work/pydev/spiketag/spiketag/base/CLU.py\", line 78, in global2local\n",
      "    clus_nos = np.unique(self.membership[global_idx])\n",
      "IndexError: index 24871 is out of bounds for axis 1 with size 24728\n",
      "ERROR: Invoking <bound method ctree_view.on_mouse_move of <ctree_view (PyQt5) at 0x7f3ba054aad0>> for MouseEvent\n"
     ]
    }
   ],
   "source": [
    "ctrl.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## spike time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "spk_time = ctrl.model.gtimes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "clu = ctrl.model.clu[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([   4,  194,  206,  300,  717,  765,  791,  819,  837,  844,  884,\n",
       "        963,  974, 1000, 1131, 1195, 1207, 1285, 1318, 1329, 1343, 1386,\n",
       "       1485, 1488, 1490, 1508, 1531, 1779, 1891, 1953, 2353, 2540, 2615,\n",
       "       2660, 2671, 2763, 2782, 2784, 2819, 2873, 2896, 2903, 2905, 2915,\n",
       "       2933, 2934, 2970, 2974, 2979, 2980, 2988, 2990, 2991, 3065, 3068,\n",
       "       3078, 3081, 3124, 3184, 3193, 3199, 3203, 3204, 3206, 3222, 3329,\n",
       "       3670, 3720, 3748, 3775, 3795, 3808, 3844, 3872, 3949, 3994, 4071,\n",
       "       4088, 4123, 4215, 4253, 4382, 4850, 4872, 5000, 5002, 5085, 5305,\n",
       "       5314, 5317, 5358, 5387, 5395, 5400, 5403, 5426, 5451, 5452, 5459,\n",
       "       5472, 5479, 5483, 5485, 5486, 5498, 5650])"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "clu.index[1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([   4,  194,  206,  300,  717,  765,  791,  819,  837,  844,  884,\n",
       "        963,  974, 1000, 1131, 1195, 1207, 1285, 1318, 1329, 1343, 1386,\n",
       "       1485, 1488, 1490, 1508, 1531, 1779, 1891, 1953, 2353, 2540, 2615,\n",
       "       2660, 2671, 2763, 2782, 2784, 2819, 2873, 2896, 2903, 2905, 2915,\n",
       "       2933, 2934, 2970, 2974, 2979, 2980, 2988, 2990, 2991, 3065, 3068,\n",
       "       3078, 3081, 3124, 3184, 3193, 3199, 3203, 3204, 3206, 3222, 3329,\n",
       "       3670, 3720, 3748, 3775, 3795, 3808, 3844, 3872, 3949, 3994, 4071,\n",
       "       4088, 4123, 4215, 4253, 4382, 4850, 4872, 5000, 5002, 5085, 5305,\n",
       "       5314, 5317, 5358, 5387, 5395, 5400, 5403, 5426, 5451, 5452, 5459,\n",
       "       5472, 5479, 5483, 5485, 5486, 5498, 5650])"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ctrl.view.spkview.selected_spk"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([  2.24868,  14.72312,  14.98536,  22.37072,  52.0672 ,  55.71692,\n",
       "        66.95588,  70.75388,  74.99176,  77.56404,  94.57788,  98.79492,\n",
       "        99.68668, 102.09396, 123.39484, 138.17644, 143.34944, 154.45956,\n",
       "       160.65976, 164.42612, 167.9042 , 169.87572, 187.8016 , 189.54756,\n",
       "       191.02852, 195.93704, 205.27016, 261.9442 , 269.19416, 274.03196,\n",
       "       326.28688, 341.2738 , 345.4662 , 346.85668, 347.85908, 354.90028,\n",
       "       356.80692, 357.617  , 358.7798 , 361.22756, 366.15008, 367.12976,\n",
       "       368.17744, 372.2744 , 375.2562 , 375.26212, 383.878  , 385.94656,\n",
       "       386.601  , 386.74452, 387.1984 , 387.3024 , 387.33016, 393.20304,\n",
       "       393.26276, 393.53116, 393.72664, 397.30676, 399.93848, 401.20504,\n",
       "       401.5546 , 403.58588, 403.5904 , 403.60868, 405.9426 , 409.01248,\n",
       "       423.25792, 425.15292, 426.52712, 428.66288, 435.0716 , 436.62464,\n",
       "       439.66552, 441.80112, 445.36852, 454.71096, 466.9398 , 467.94568,\n",
       "       470.79692, 495.63668, 497.45336, 517.71364, 552.32448, 555.71384,\n",
       "       584.73844, 584.86032, 590.32584, 624.66132, 626.2468 , 626.34356,\n",
       "       631.217  , 633.6626 , 633.94912, 634.08988, 634.20068, 638.3944 ,\n",
       "       643.02848, 643.0588 , 645.99168, 647.00424, 647.89892, 648.15536,\n",
       "       648.3118 , 648.72044, 650.02172, 681.96248])"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "spk_time[0][clu.index[1]]/25000."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
